### ISSUE TITLE
Missing meta data

### ISSUE THREAD

**Issue by sarigs** [CheckPointSW/Cyber-Research#2]
Dear Developer, 

 For readability and Search Engine Optimization (SEO) it would be great if you could do the followings:
- [x] Please provide more than 8 words in the "About" field
- [x] Please provide README.md file with more than 150 chars

**Comment by chkp-eyalit** [comment]
Added a README description to each of the sub-folders, and also a more broader one to the main README.md of the repository. Also added the relevant topics, and created an "About" description.

In cases that anything is missing / needs further work, feel free to re-open this ticket.
